fix: "/fansub/[slug]" is missing "generateStaticParams()"
> Build error occurred
Error: Page "/fansub/[slug]" is missing "generateStaticParams()" so it cannot be used with "output: export" config.